### ISSUE TITLE
Implementation with AMQP (RabbitMQ)

### ISSUE THREAD

**Issue by oscarvesga** [wso2-ballerina/module-storeforward#10]
**Description:**
Hello, there is any date in which we can see an implementation of this module using the AMQP protocol? I would really apreciate that.

**Suggested Labels:**
AQMP, suggested

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
